module.exports = {
  Synth:     'note',
  FM:        'note',
  Monosynth: 'note',
  Complex:   'note',
  Sampler:   'pickplay',
  Snare:     'trigger',
  Kick:      'trigger',
  Clave:     'trigger',
  Tom:       'note:',
  Clap:      'trigger',
  Hat:       'trigger',
  Pluck:     'note',
  Karplus:   'note',
  Soundfont: 'note',
  Conga:     'note',
  PolySynth: 'note',
  PolyFM:    'note',
  PolyMono:  'note',
  PolyComplex:'note',
  Multisampler:'pickplay',
  Grains:'pickplay',
  PolyConga: 'note',
  PolyTom:   'note',
  PolyKarplus:'note'
}
